apiVersion: v1
kind: Service
metadata:
  name: cloudbench-tests
spec:
  selector:
    app: cloudbench
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbench
spec:
  selector:
    matchLabels:
      app: cloudbench
  replicas: 4
  template:
    metadata:
      labels:
        app: cloudbench
    spec:
      containers:
      - name: cloudbench
        image: reillym/cloudbench:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
